/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Size = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'xLarge' : IDL.Null,
  'medium' : IDL.Null,
});
export const Category = IDL.Variant({
  'dresses' : IDL.Null,
  'abayas' : IDL.Null,
  'ethnicSets' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Size = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'xLarge' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Category = IDL.Variant({
    'dresses' : IDL.Null,
    'abayas' : IDL.Null,
    'ethnicSets' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };